import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Attenad</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-full flex-col items-center justify-center gap-3 border">
        <span className="text-xl tracking-wide">
          APU attendance system with RFID technology
        </span>

        <div className="flex flex-col items-center">
          <span>By</span>

          <span className="bg-secondary px-4  tracking-widest">
            Dylan Toh Voo Chieng
          </span>
        </div>
      </main>
    </>
  );
};

export default Home;
